**Importing Libraries**

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import pandas_datareader as DataReader
from datetime import date

**Loading & Analyszing Datasets**

In [12]:
Order_Report = pd.read_excel('/content/Company X - Order Report.xlsx')
Order_Report.info()
Order_Report.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ExternOrderNo         400 non-null    int64
 1   SKU                   400 non-null    object
 2   Order Qty             400 non-null    int64
 3   Payment Mode          400 non-null    object
 4   Item Price(Per Qty.)  400 non-null    int64
dtypes: int64(3), object(2)
memory usage: 15.8+ KB

   ExternOrderNo            SKU  Order Qty Payment Mode  Item Price(Per Qty.)
0     2001827036  8904223818706          1          COD                   233
1     2001827036  8904223819093          1          COD                   233
2     2001827036  8904223819109          1          COD                   233
3     2001827036  8904223818430          1          COD                   470
4     2001827036  8904223819277          1          COD                   233

In [13]:
Order_Report.rename(columns={"ExternOrderNo":"Order ID"},inplace=True)
Order_Report.head()

     Order ID            SKU  Order Qty Payment Mode  Item Price(Per Qty.)
0  2001827036  8904223818706          1          COD                   233
1  2001827036  8904223819093          1          COD                   233
2  2001827036  8904223819109          1          COD                   233
3  2001827036  8904223818430          1          COD                   470
4  2001827036  8904223819277          1          COD                   233

In [14]:
Pincode=pd.read_excel('/content/Company X - Pincode Zones.xlsx')
Pincode.info()
Pincode.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Warehouse Pincode  124 non-null    int64
 1   Customer Pincode   124 non-null    int64
 2   Zone               124 non-null    object
dtypes: int64(2), object(1)
memory usage: 3.0+ KB

   Warehouse Pincode  Customer Pincode Zone
0             121003            507101    d
1             121003            486886    d
2             121003            532484    d
3             121003            143001    b
4             121003            515591    d

In [15]:
Pincode.rename(columns={"Zone":"Delivery Zone as Per Company X"},inplace=True)
Pincode.head()

   Warehouse Pincode  Customer Pincode Delivery Zone as Per Company X
0             121003            507101                              d
1             121003            486886                              d
2             121003            532484                              d
3             121003            143001                              b
4             121003            515591                              d

In [16]:
SKU=pd.read_excel('/content/Company X - SKU Master.xlsx')
SKU.info()
SKU.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   SKU         66 non-null     object
 1   Weight (g)  66 non-null     int64
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

             SKU  Weight (g)
0  8904223815682         210
1  8904223815859         165
2  8904223815866         113
3  8904223815873          65
4  8904223816214         120

In [17]:
CourierInvoice= pd.read_excel('/content/Courier Company - Invoice.xlsx')
CourierInvoice.info()
CourierInvoice.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124 entries, 0 to 123
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   AWB Code              124 non-null    int64
 1   Order ID              124 non-null    int64
 2   Charged Weight        124 non-null    float64
 3   Warehouse Pincode     124 non-null    int64
 4   Customer Pincode      124 non-null    int64
 5   Zone                  124 non-null    object
 6   Type of Shipment      124 non-null    object
 7   Billing Amount (Rs.)  124 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 7.9+ KB

,AWB Code,Order ID,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.)
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0
1,1091117222194,2001806273,1.00,121003,486886,d,Forward charges,101.2
2,1091117222931,2001806408,2.50,121003,532484,d,Forward charges,224.6
3,1091117223244,2001806458,1.00,121003,143001,b,Forward charges,61.3
4,1091117229345,2001807012,0.15,121003,515591,d,Forward charges,45.4

In [67]:
CourierInvoice.rename(columns = {"Zone":"Delivery Zone Charged By Courier Company","Charged Weight":"Total Weight As Per Courier Company (KG)"},inplace=True)
CourierInvoice.head()

,AWB Code,Order ID,Total Weight As Per Courier Company (KG),Warehouse Pincode,Customer Pincode,Delivery Zone Charged By Courier Company,Type of Shipment,Billing Amount (Rs.),Weight Slab Charged By Courier Company (KG)
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0,1.5
1,1091117222194,2001806273,1.00,121003,486886,d,Forward charges,101.2,1.0
2,1091117222931,2001806408,2.50,121003,532484,d,Forward charges,224.6,2.5
3,1091117223244,2001806458,1.00,121003,143001,b,Forward charges,61.3,1.0
4,1091117229345,2001807012,0.15,121003,515591,d,Forward charges,45.4,0.5

In [81]:
Rates= pd.read_excel('/content/Courier Company - Rates.xlsx')
Rates.info()
Rates.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Zone                                   5 non-null      object
 1   Weight Slabs                           5 non-null      float64
 2   Forward Fixed Charge                   5 non-null      float64
 3   Forward Additional Weight Slab Charge  5 non-null      float64
 4   RTO Fixed Charge                       5 non-null      float64
 5   RTO Additional Weight Slab Charge      5 non-null      float64
dtypes: float64(5), object(1)
memory usage: 368.0+ bytes

,Zone,Weight Slabs,Forward Fixed Charge,Forward Additional Weight Slab Charge,RTO Fixed Charge,RTO Additional Weight Slab Charge
0,A,0.25,29.5,23.6,13.6,23.6
1,B,0.50,33.0,28.3,20.5,28.3
2,C,0.75,40.1,38.9,31.9,38.9
3,D,1.25,45.4,44.8,41.3,44.8
4,E,1.50,56.6,55.5,50.7,55.5

**EDA:** Exploratory Data Analysis refers to the crucial process of performing initial investigations on data to discover patterns to check assumptions with the help of summary statistics and graphical representations.
* Can be leveraged to check for outliers, patterns, and trends in the given data.
* Helps to find meaningful patterns in data.
* Gives a clue to impute missing values in the dataset
* Provides in-depth insights into the data sets to solve our business problems.

In [82]:
MergeSKU_Order=pd.merge(Order_Report,SKU,how="left",on="SKU")
MergeSKU_Order.info()
MergeSKU_Order.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 401 entries, 0 to 400
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order ID              401 non-null    int64
 1   SKU                   401 non-null    object
 2   Order Qty             401 non-null    int64
 3   Payment Mode          401 non-null    object
 4   Item Price(Per Qty.)  401 non-null    int64
 5   Weight (g)            401 non-null    int64
dtypes: int64(4), object(2)
memory usage: 21.9+ KB

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Weight (g)
0,2001827036,8904223818706,1,COD,233,127
1,2001827036,8904223819093,1,COD,233,150
2,2001827036,8904223819109,1,COD,233,100
3,2001827036,8904223818430,1,COD,470,165
4,2001827036,8904223819277,1,COD,233,350

**Removing Missing Elements from Datasets**

In [83]:
MergeSKU_Order.dropna()

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Weight (g)
0,2001827036,8904223818706,1,COD,233,127
1,2001827036,8904223819093,1,COD,233,150
2,2001827036,8904223819109,1,COD,233,100
3,2001827036,8904223818430,1,COD,470,165
4,2001827036,8904223819277,1,COD,233,350
...,...,...,...,...,...,...
396,2001806229,8904223818942,1,COD,286,133
397,2001806229,8904223818850,1,COD,563,240
398,2001806226,8904223818850,2,COD,1125,240
399,2001806210,8904223816214,1,COD,402,120
400,2001806210,8904223818874,1,COD,922,100

In [84]:
MergeCourier=Pincode.drop_duplicates(subset=['Customer Pincode'])
MergeCourier_X=CourierInvoice[['Order ID', 'Customer Pincode','Type of Shipment']]
MergePincode=MergeCourier_X.merge(MergeCourier,on='Customer Pincode')
MergePincode.head()

,Order ID,Customer Pincode,Type of Shipment,Warehouse Pincode,Delivery Zone as Per Company X
0,2001806232,507101,Forward charges,121003,d
1,2001806273,486886,Forward charges,121003,d
2,2001806408,532484,Forward charges,121003,d
3,2001806458,143001,Forward charges,121003,b
4,2001807012,515591,Forward charges,121003,d

In [85]:
SKU_Merge=MergeSKU_Order.merge(MergePincode,on='Order ID')
SKU_Merge.head()

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Weight (g),Customer Pincode,Type of Shipment,Warehouse Pincode,Delivery Zone as Per Company X
0,2001827036,8904223818706,1,COD,233,127,173213,Forward charges,121003,e
1,2001827036,8904223819093,1,COD,233,150,173213,Forward charges,121003,e
2,2001827036,8904223819109,1,COD,233,100,173213,Forward charges,121003,e
3,2001827036,8904223818430,1,COD,470,165,173213,Forward charges,121003,e
4,2001827036,8904223819277,1,COD,233,350,173213,Forward charges,121003,e

In [88]:
kg=1000
SKU_rename=SKU_Merge.rename(columns={"Order Qty":"Order_Qty","Weight (g)":"Weight_g"})

In [89]:
convert_g_to_kg="""
Total_Weight_Per_Shipment=(Order_Qty*Weight_g)/@kg
 """
SKU_rename.eval(convert_g_to_kg,inplace=True,engine='python')
SKU_rename['Weight_g'].value_counts()

240    98
127    59
133    41
112    40
120    22
350    19
210    15
165    15
121    12
100    11
115     8
290     8
65      7
113     5
137     5
500     5
140     4
130     4
600     4
232     3
10      3
150     2
110     2
170     2
490     1
160     1
250     1
102     1
30      1
300     1
552     1
Name: Weight_g, dtype: int64

In [90]:
SKU_rename['Type of Shipment'].value_counts()

Forward charges            351
Forward and RTO charges     50
Name: Type of Shipment, dtype: int64

In [91]:
SKU_rename

,Order ID,SKU,Order_Qty,Payment Mode,Item Price(Per Qty.),Weight_g,Customer Pincode,Type of Shipment,Warehouse Pincode,Delivery Zone as Per Company X,Total_Weight_Per_Shipment
0,2001827036,8904223818706,1,COD,233,127,173213,Forward charges,121003,e,0.127
1,2001827036,8904223819093,1,COD,233,150,173213,Forward charges,121003,e,0.150
2,2001827036,8904223819109,1,COD,233,100,173213,Forward charges,121003,e,0.100
3,2001827036,8904223818430,1,COD,470,165,173213,Forward charges,121003,e,0.165
4,2001827036,8904223819277,1,COD,233,350,173213,Forward charges,121003,e,0.350
...,...,...,...,...,...,...,...,...,...,...,...
396,2001806229,8904223818942,1,COD,286,133,421204,Forward charges,121003,d,0.133
397,2001806229,8904223818850,1,COD,563,240,421204,Forward charges,121003,d,0.240
398,2001806226,8904223818850,2,COD,1125,240,723146,Forward charges,121003,d,0.480
399,2001806210,8904223816214,1,COD,402,120,140604,Forward charges,121003,b,0.120
400,2001806210,8904223818874,1,COD,922,100,140604,Forward charges,121003,b,0.100

In [92]:
renameSKU=SKU_rename.rename(columns={"Order_Qty":"Order Qty","Total_Weight_Per_Shipment":"Total Weight AS Per Company X (KG)","Weight_g":"Weight (g)"})
renameSKU.head()

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Weight (g),Customer Pincode,Type of Shipment,Warehouse Pincode,Delivery Zone as Per Company X,Total Weight AS Per Company X (KG)
0,2001827036,8904223818706,1,COD,233,127,173213,Forward charges,121003,e,0.127
1,2001827036,8904223819093,1,COD,233,150,173213,Forward charges,121003,e,0.150
2,2001827036,8904223819109,1,COD,233,100,173213,Forward charges,121003,e,0.100
3,2001827036,8904223818430,1,COD,470,165,173213,Forward charges,121003,e,0.165
4,2001827036,8904223819277,1,COD,233,350,173213,Forward charges,121003,e,0.350

**Categorzing and Assiging the Weight Range Slab.**

In [93]:
def weight_slab(weight):
    decimal_part = weight - int(weight)

    if decimal_part == 0.0:
        return weight
    elif decimal_part > 0.5:
        return int(weight) + 1.0
    else:
        return int(weight) + 0.5

**Slab Weight Generation**

In [94]:
renameSKU['Weight Slab As Per Company X (KG)']=renameSKU['Total Weight AS Per Company X (KG)'].apply(weight_slab)
CourierInvoice['Weight Slab Charged By Courier Company (KG)']=(CourierInvoice['Total Weight As Per Courier Company (KG)']).apply(weight_slab)
renameSKU.head()

,Order ID,SKU,Order Qty,Payment Mode,Item Price(Per Qty.),Weight (g),Customer Pincode,Type of Shipment,Warehouse Pincode,Delivery Zone as Per Company X,Total Weight AS Per Company X (KG),Weight Slab As Per Company X (KG)
0,2001827036,8904223818706,1,COD,233,127,173213,Forward charges,121003,e,0.127,0.5
1,2001827036,8904223819093,1,COD,233,150,173213,Forward charges,121003,e,0.150,0.5
2,2001827036,8904223819109,1,COD,233,100,173213,Forward charges,121003,e,0.100,0.5
3,2001827036,8904223818430,1,COD,470,165,173213,Forward charges,121003,e,0.165,0.5
4,2001827036,8904223819277,1,COD,233,350,173213,Forward charges,121003,e,0.350,0.5

In [95]:
CourierInvoice.head()

,AWB Code,Order ID,Total Weight As Per Courier Company (KG),Warehouse Pincode,Customer Pincode,Delivery Zone Charged By Courier Company,Type of Shipment,Billing Amount (Rs.),Weight Slab Charged By Courier Company (KG)
0,1091117222124,2001806232,1.30,121003,507101,d,Forward charges,140.0,1.5
1,1091117222194,2001806273,1.00,121003,486886,d,Forward charges,101.2,1.0
2,1091117222931,2001806408,2.50,121003,532484,d,Forward charges,224.6,2.5
3,1091117223244,2001806458,1.00,121003,143001,b,Forward charges,61.3,1.0
4,1091117229345,2001807012,0.15,121003,515591,d,Forward charges,45.4,0.5

**Calculation of Expected Charges Based on Delivery Zone and Weight Slab.**

In [99]:
def calculate_expected_charge(row, courier_rates):
    zone = row['Delivery Zone as Per Company X']
    fwd_category = 'fwd_' + zone
    rto_category = 'rto_' + zone

    if fwd_category + '_fixed' in courier_rates.columns and fwd_category + '_additional' in courier_rates.columns:
        fwd_fixed = courier_rates.at[0, fwd_category + '_fixed']
        fwd_additional = courier_rates.at[0, fwd_category + '_additional']
    else:
        return 0  # Handle missing keys

    if rto_category + '_fixed' in courier_rates.columns and rto_category + '_additional' in courier_rates.columns:
        rto_fixed = courier_rates.at[0, rto_category + '_fixed']
        rto_additional = courier_rates.at[0, rto_category + '_additional']
    else:
        return 0  # Handle missing keys

    weight_slab = row['Weight Slab As Per Company X (KG)']
    shipment_type = row['Type of Shipment']

    if weight_slab <= 0.5:
        if shipment_type == 'Forward charges':
            return fwd_fixed
        elif shipment_type == 'Forward and RTO charges':
            return fwd_fixed + rto_fixed
    else:
        additional_weight = (weight_slab - 0.5) / 0.5
        if shipment_type == 'Forward charges':
            return fwd_fixed + additional_weight * fwd_additional
        elif shipment_type == 'Forward and RTO charges':
            return fwd_fixed + additional_weight * (fwd_additional + rto_additional)

    return 0  # Default case if conditions are not met

# Calculate and assign expected charges
renameSKU['Expected Charge As Per Company X (Rs.)'] = renameSKU.apply(
    lambda row: calculate_expected_charge(row, Rates),
    axis=1)

In [100]:
renameSKU.columns

Index(['Order ID', 'SKU', 'Order Qty', 'Payment Mode', 'Item Price(Per Qty.)',
       'Weight (g)', 'Customer Pincode', 'Type of Shipment',
       'Warehouse Pincode', 'Delivery Zone as Per Company X',
       'Total Weight AS Per Company X (KG)',
       'Weight Slab As Per Company X (KG)',
       'Expected Charge As Per Company X (Rs.)'],
      dtype='object')

In [101]:
Result=renameSKU[['Order ID','Type of Shipment', 'Payment Mode','Item Price(Per Qty.)', 'Delivery Zone as Per Company X',
                 'Total Weight AS Per Company X (KG)', 'Weight Slab As Per Company X (KG)',
       'Expected Charge As Per Company X (Rs.)']]

In [103]:
CourierInvoice.columns

Index(['AWB Code', 'Order ID', 'Total Weight As Per Courier Company (KG)',
       'Warehouse Pincode', 'Customer Pincode',
       'Delivery Zone Charged By Courier Company', 'Type of Shipment',
       'Billing Amount (Rs.)', 'Weight Slab Charged By Courier Company (KG)'],
      dtype='object')

In [104]:
Result2=CourierInvoice[['AWB Code', 'Order ID','Total Weight As Per Courier Company (KG)',
        'Delivery Zone Charged By Courier Company','Billing Amount (Rs.)', 'Weight Slab Charged By Courier Company (KG)']]

In [105]:
Merged_Result=Result.merge(Result2,on='Order ID',how='left')
Merged_Result.head()

,Order ID,Type of Shipment,Payment Mode,Item Price(Per Qty.),Delivery Zone as Per Company X,Total Weight AS Per Company X (KG),Weight Slab As Per Company X (KG),Expected Charge As Per Company X (Rs.),AWB Code,Total Weight As Per Courier Company (KG),Delivery Zone Charged By Courier Company,Billing Amount (Rs.),Weight Slab Charged By Courier Company (KG)
0,2001827036,Forward charges,COD,233,e,0.127,0.5,0,1091122418320,1.6,b,117.9,2.0
1,2001827036,Forward charges,COD,233,e,0.150,0.5,0,1091122418320,1.6,b,117.9,2.0
2,2001827036,Forward charges,COD,233,e,0.100,0.5,0,1091122418320,1.6,b,117.9,2.0
3,2001827036,Forward charges,COD,470,e,0.165,0.5,0,1091122418320,1.6,b,117.9,2.0
4,2001827036,Forward charges,COD,233,e,0.350,0.5,0,1091122418320,1.6,b,117.9,2.0

In [119]:
Resultant_Output=Merged_Result.copy()

In [123]:
Resultant_Output=Resultant_Output.rename(columns={'AWB Code':'AWB Number','Billing Amount (Rs.)':'Charges_Billed_By_Courier_Company_Rs','Expected Charge As Per Company X (Rs.)':'Expected_Charge_As_Per_Company_Rs'})
Resultant_Output.head()

,Order ID,Type of Shipment,Payment Mode,Item Price(Per Qty.),Delivery Zone as Per Company X,Total Weight AS Per Company X (KG),Weight Slab As Per Company X (KG),Expected_Charge_As_Per_Company_Rs,AWB Number,Total Weight As Per Courier Company (KG),Delivery Zone Charged By Courier Company,Charges_Billed_By_Courier_Company_Rs,Weight Slab Charged By Courier Company (KG)
0,2001827036,Forward charges,COD,233,e,0.127,0.5,0,1091122418320,1.6,b,117.9,2.0
1,2001827036,Forward charges,COD,233,e,0.150,0.5,0,1091122418320,1.6,b,117.9,2.0
2,2001827036,Forward charges,COD,233,e,0.100,0.5,0,1091122418320,1.6,b,117.9,2.0
3,2001827036,Forward charges,COD,470,e,0.165,0.5,0,1091122418320,1.6,b,117.9,2.0
4,2001827036,Forward charges,COD,233,e,0.350,0.5,0,1091122418320,1.6,b,117.9,2.0

**Calculation of Variance Between Expected Charges and Billed Amounts**

In [124]:
diff_bw_ec_bc="""
Difference_Between_Expected_Charges_and_Billed_Charges_Rs =(Expected_Charge_As_Per_Company_Rs - Charges_Billed_By_Courier_Company_Rs)
"""
Resultant_Output.eval(diff_bw_ec_bc,inplace=True,engine='python')

In [125]:
Resultant_Output=Resultant_Output.rename(columns={'Charges_Billed_By_Courier_Company_Rs':'Charges Billed By Courier Company (Rs.)','Expected_Charge_As_Per_Company_Rs':'Expected Charge As Per Company X (Rs.)','Difference_Between_Expected_Charges_and_Billed_Charges_Rs':'Difference Between Expected Charges And Billed Charges (Rs.)'})

In [126]:
writer = pd.ExcelWriter('Expected_Result.xlsx',if_sheet_exists="replace",engine='openpyxl',mode="a")

In [127]:
Resultant_Output.to_excel(writer,sheet_name='Calculations')
calculations=writer.save()

<ipython-input-127-d8b29fde2108>:2: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  calculations=writer.save()

**Calculation of Total Orders**

In [132]:
correctly_charged=Resultant_Output[Resultant_Output['Difference Between Expected Charges And Billed Charges (Rs.)']==0.0]
correctly=["Total No of Accurate Charges",len(correctly_charged),sum(correctly_charged['Charges Billed By Courier Company (Rs.)'])]

over_charged=Resultant_Output[Resultant_Output['Difference Between Expected Charges And Billed Charges (Rs.)']<0.0]
over=["Total No of Excessive Charges ",len(over_charged),np.absolute(sum(over_charged['Difference Between Expected Charges And Billed Charges (Rs.)']))]

under_charged=Resultant_Output[Resultant_Output['Difference Between Expected Charges And Billed Charges (Rs.)']>0.0]
under=["Total No of Under Charges",len(under_charged),np.absolute(sum(under_charged['Difference Between Expected Charges And Billed Charges (Rs.)']))]

In [134]:
Resultant_Output2=pd.DataFrame([correctly,over,under],columns=['Description','Count','Amount (Rs.)'])
Resultant_Output2

                      Description  Count  Amount (Rs.)
0    Total No of Accurate Charges      0           0.0
1  Total No of Excessive Charges     401       50432.5
2       Total No of Under Charges      0           0.0

In [135]:
Resultant_Output2.to_excel(writer,sheet_name='Summary')
writer.save()

<ipython-input-135-8278eb61c5a4>:2: FutureWarning: save is not part of the public API, usage can give unexpected results and will be removed in a future version
  writer.save()

In [139]:
df_sheet_multi = pd.read_excel('Expected_Result.xlsx', sheet_name=['Calculations', 'Summary'])
df_sheet_multi['Calculations']

,Unnamed: 0,Order ID,Type of Shipment,Payment Mode,Item Price(Per Qty.),Delivery Zone as Per Company X,Total Weight AS Per Company X (KG),Weight Slab As Per Company X (KG),Expected Charge As Per Company X (Rs.),AWB Number,Total Weight As Per Courier Company (KG),Delivery Zone Charged By Courier Company,Charges Billed By Courier Company (Rs.),Weight Slab Charged By Courier Company (KG),Difference Between Expected Charges And Billed Charges (Rs.)
0,0,2001827036,Forward charges,COD,233,e,0.127,0.5,0,1091122418320,1.60,b,117.9,2.0,-117.9
1,1,2001827036,Forward charges,COD,233,e,0.150,0.5,0,1091122418320,1.60,b,117.9,2.0,-117.9
2,2,2001827036,Forward charges,COD,233,e,0.100,0.5,0,1091122418320,1.60,b,117.9,2.0,-117.9
3,3,2001827036,Forward charges,COD,470,e,0.165,0.5,0,1091122418320,1.60,b,117.9,2.0,-117.9
4,4,2001827036,Forward charges,COD,233,e,0.350,0.5,0,1091122418320,1.60,b,117.9,2.0,-117.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,396,2001806229,Forward charges,COD,286,d,0.133,0.5,0,1091117222080,0.71,d,90.2,1.0,-90.2
397,397,2001806229,Forward charges,COD,563,d,0.240,0.5,0,1091117222080,0.71,d,90.2,1.0,-90.2
398,398,2001806226,Forward charges,COD,1125,d,0.480,0.5,0,1091117222065,0.68,d,90.2,1.0,-90.2
399,399,2001806210,Forward charges,COD,402,b,0.120,0.5,0,1091117221940,2.92,b,174.5,3.0,-174.5
400,400,2001806210,Forward charges,COD,922,b,0.100,0.5,0,1091117221940,2.92,b,174.5,3.0,-174.5

In [138]:
df_sheet_multi['Summary']

   Unnamed: 0                     Description  Count  Amount (Rs.)
0           0    Total No of Accurate Charges      0           0.0
1           1  Total No of Excessive Charges     401       50432.5
2           2       Total No of Under Charges      0           0.0